'use strict';

const { getDb } = require('../db/database');
const { aggregateWeeklyReport } = require('../engine/weeklyReport');

// GET /:userId/weekly
function getWeeklySummary(userId, weekEndDate = null) {
  const db = getDb();
  return aggregateWeeklyReport(db, userId, weekEndDate);
}

// POST /:userId/weekly/narrative
// Returns the summary plus a human-readable prompt string for the cloud LLM.
// The actual narrative is generated by POST /ai/weekly-report.
function getWeeklyNarrative(userId, weekEndDate = null) {
  const db      = getDb();
  const summary = aggregateWeeklyReport(db, userId, weekEndDate);

  // Build a human-readable summary string for the LLM prompt.
  const summaryLines = [
    `Period: ${summary.period.start} to ${summary.period.end}`,
    `Workouts: ${summary.workouts.completed}/${summary.workouts.planned} completed (${summary.workouts.adherence_pct ?? '?'}% adherence)`,
    `Average RPE: ${summary.workouts.avg_rpe ?? 'not logged'}`,
    `Total tonnage: ${summary.workouts.total_tonnage_kg} kg`,
    summary.strength.map(s =>
      `${s.exercise_name}: ${s.this_week_kg ?? '?'} kg this week` +
      (s.change_kg !== null ? ` (${s.change_kg > 0 ? '+' : ''}${s.change_kg} kg vs last week)` : '')
    ).join('\n'),
    `Check-in days logged: ${summary.checkins.days_logged}/7`,
    `Average energy: ${summary.checkins.avg_energy ?? '?'}/10`,
    `Symptom days: ${summary.checkins.symptom_days}`,
    summary.activity.days_logged
      ? `Steps: avg ${summary.activity.avg_steps ?? '?'}/day over ${summary.activity.days_logged} day(s), step goal hit ${summary.activity.step_goal_hit_days} day(s)`
      : 'No step data logged this week',
    summary.activity.cardio_sessions
      ? `Cardio: ${summary.activity.cardio_sessions} session(s), ${summary.activity.cardio_minutes} min total (easy ${summary.activity.cardio_by_intensity.easy} / moderate ${summary.activity.cardio_by_intensity.moderate} / hard ${summary.activity.cardio_by_intensity.hard})`
      : '',
    `Lean-mass proxy: ${summary.lean_mass_proxy.score ?? 'no measurements'} — ${summary.lean_mass_proxy.summary}`,
    summary.body_weight.this_week_kg ? `Weight: ${summary.body_weight.this_week_kg} kg (4-week trend: ${summary.body_weight.trend_4wk_kg ?? '?'} kg)` : 'No weight logged',
    summary.drug_context.in_titration_window ? `Note: User is in titration window (day ${summary.drug_context.days_since_dose_change} of 14 after dose change)` : '',
  ].filter(Boolean).join('\n');

  return {
    summary,
    narrative_prompt: summaryLines,
    narrative: null, // populated when POST /ai/weekly-report is called
    message: 'Send narrative_prompt to POST /ai/weekly-report to generate the written summary.',
  };
}

module.exports = { getWeeklySummary, getWeeklyNarrative };
