-- Migration 001: users table
-- Stores the core identity record for each person who signs up.
-- apple_user_id comes from Sign in with Apple.
-- email is optional (users who sign in with Apple may not share it).

CREATE TABLE IF NOT EXISTS users (
  id             TEXT PRIMARY KEY,          -- UUID generated by the backend
  apple_user_id  TEXT UNIQUE,               -- the stable identifier Apple gives us
  email          TEXT,                      -- may be null or a relay address from Apple
  display_name   TEXT,
  created_at     DATETIME NOT NULL DEFAULT (datetime('now')),
  updated_at     DATETIME NOT NULL DEFAULT (datetime('now'))
);

-- Speed up lookups by Apple user ID (happens on every login).
CREATE INDEX IF NOT EXISTS idx_users_apple_user_id ON users(apple_user_id);
