-- Migration 013: seed the movements library
-- 72 vetted movements (locked 2026-06-20). See Phase1_Movement_Candidate_List.md.
-- Rows inserted first with NULL chains, then progression/substitution links
-- applied via UPDATE so foreign keys resolve regardless of insert order.

INSERT INTO movements (id,name,aliases,category,pattern,primary_muscles,secondary_muscles,equipment,level,is_compound,unilateral,tempo_default,glp_flag,notes) VALUES
  ('push_up', 'Push-Up', '["pushup", "press up"]', 'push', 'push_h', '["chest", "triceps", "front_delt", "core"]', '[]', 'bodyweight', 'beginner', 1, 0, '3-0-1-0', 1, 'Hands shoulder-width. 3-second descent. Incline (hands elevated) reduces difficulty.'),
  ('incline_push_up', 'Incline Push-Up', '["hands-elevated push-up", "easy push-up"]', 'push', 'push_h', '["chest", "triceps", "front_delt"]', '["core"]', 'bodyweight', 'beginner', 1, 0, '3-0-1-0', 1, 'Hands on a bench or counter. Easiest regression for pressing.'),
  ('db_bench_press', 'Dumbbell Bench Press', '["db bench", "dumbbell press", "flat db press"]', 'push', 'push_h', '["chest", "triceps", "front_delt"]', '[]', 'dumbbell', 'beginner', 1, 0, '3-0-1-0', 1, '3-second descent to chest. Safer than barbell for solo trainers.'),
  ('machine_chest_press', 'Machine Chest Press', '["chest press machine", "seated chest press"]', 'push', 'push_h', '["chest", "triceps", "front_delt"]', '[]', 'machine', 'beginner', 1, 0, '3-0-1-0', 1, 'Fixed path — good for beginners. Control the return.'),
  ('incline_db_press', 'Incline Dumbbell Press', '["incline db press", "incline dumbbell"]', 'push', 'push_h', '["upper_chest", "front_delt", "triceps"]', '[]', 'dumbbell', 'intermediate', 1, 0, '3-0-1-0', 1, '30-45 degree incline. 3-second descent.'),
  ('cable_fly', 'Cable Chest Fly', '["cable flye", "pec fly", "crossover"]', 'push', 'push_h', '["chest"]', '["front_delt"]', 'cable', 'intermediate', 0, 0, '2-0-1-0', 1, 'Soft elbows. Squeeze across the midline. Stretch under control.'),
  ('db_floor_press', 'Dumbbell Floor Press', '["floor press"]', 'push', 'push_h', '["chest", "triceps"]', '["front_delt"]', 'dumbbell', 'intermediate', 1, 0, '3-0-1-0', 1, 'Triceps elbow lightly touches floor each rep. Shoulder-friendly.'),
  ('barbell_bench_press', 'Barbell Bench Press', '["bench", "bench press", "flat bench"]', 'push', 'push_h', '["chest", "triceps", "front_delt"]', '[]', 'barbell', 'advanced', 1, 0, '3-0-1-0', 1, '3-second descent. Spotter or safety pins recommended.'),
  ('db_shoulder_press', 'Dumbbell Shoulder Press', '["db ohp", "seated db press", "dumbbell shoulder"]', 'push', 'push_v', '["front_delt", "side_delt", "triceps"]', '[]', 'dumbbell', 'beginner', 1, 0, '3-0-1-0', 1, 'Seated for stability. 3-second descent. Don''t lock out elbows.'),
  ('machine_shoulder_press', 'Machine Shoulder Press', '["shoulder press machine"]', 'push', 'push_v', '["front_delt", "side_delt", "triceps"]', '[]', 'machine', 'beginner', 1, 0, '3-0-1-0', 1, 'Fixed path overhead press. Good when balance or shoulder confidence is low.'),
  ('db_lateral_raise', 'Dumbbell Lateral Raise', '["lat raise", "side raise", "lateral"]', 'push', 'push_v', '["side_delt"]', '[]', 'dumbbell', 'beginner', 0, 0, '2-0-1-0', 1, 'Lead with the elbows. Light weight, controlled. No swinging.'),
  ('arnold_press', 'Arnold Press', '["arnold"]', 'push', 'push_v', '["front_delt", "side_delt", "triceps"]', '[]', 'dumbbell', 'intermediate', 1, 0, '3-0-1-0', 1, 'Rotate palms from facing-in to facing-out as you press.'),
  ('barbell_ohp', 'Barbell Overhead Press', '["ohp", "overhead press", "military press", "strict press"]', 'push', 'push_v', '["front_delt", "side_delt", "triceps", "upper_back"]', '[]', 'barbell', 'advanced', 1, 0, '3-0-1-0', 0, 'Standing. Brace hard. Press over the forehead.'),
  ('chest_supported_row', 'Chest-Supported Row', '["chest supported", "seal row", "incline row"]', 'pull', 'pull_h', '["mid_back", "rear_delt", "biceps"]', '[]', 'dumbbell', 'beginner', 1, 0, '3-0-1-0', 1, 'Chest on incline pad. No lower back involvement. Great for beginners.'),
  ('db_row', 'Single-Arm Dumbbell Row', '["one arm row", "db row", "single arm row"]', 'pull', 'pull_h', '["lats", "mid_back", "biceps"]', '[]', 'dumbbell', 'beginner', 1, 1, '3-0-1-0', 1, 'Knee on bench. Pull elbow to hip. 3-second descent. Full stretch at bottom.'),
  ('cable_row', 'Seated Cable Row', '["seated row", "cable row", "machine row"]', 'pull', 'pull_h', '["lats", "mid_back", "biceps"]', '[]', 'cable', 'beginner', 1, 0, '3-0-1-0', 1, 'Sit tall. Pull to lower chest. 3-second return. Don''t lean back excessively.'),
  ('inverted_row', 'Inverted Row', '["bodyweight row", "ring row", "table row"]', 'pull', 'pull_h', '["mid_back", "lats", "biceps"]', '["rear_delt", "core"]', 'bodyweight', 'intermediate', 1, 0, '3-0-1-0', 1, 'Body straight, heels down. Higher bar = easier. Squeeze shoulder blades.'),
  ('barbell_row', 'Barbell Row', '["bent over row", "bb row", "pendlay row"]', 'pull', 'pull_h', '["lats", "mid_back", "biceps", "lower_back"]', '[]', 'barbell', 'advanced', 1, 0, '3-0-1-0', 0, 'Hinge forward 45 degrees. Pull to belly button.'),
  ('lat_pulldown', 'Lat Pulldown', '["pulldown", "lat pull"]', 'pull', 'pull_v', '["lats", "biceps", "rear_delt"]', '[]', 'cable', 'beginner', 1, 0, '3-0-1-0', 1, 'Wide overhand grip. Pull bar to upper chest. 3-second return.'),
  ('straight_arm_pulldown', 'Straight-Arm Pulldown', '["lat pushdown", "straight arm"]', 'pull', 'pull_v', '["lats"]', '["triceps"]', 'cable', 'beginner', 0, 0, '2-0-1-0', 1, 'Arms straight, drive the bar to your thighs. Feel the lats, not the arms.'),
  ('assisted_pull_up', 'Assisted Pull-Up', '["assisted pullup", "band pull-up"]', 'pull', 'pull_v', '["lats", "biceps"]', '[]', 'machine', 'intermediate', 1, 0, '3-0-1-0', 1, 'Dead hang at bottom. Full range. 3-second descent.'),
  ('pull_up', 'Pull-Up', '["pullup", "chin up"]', 'pull', 'pull_v', '["lats", "biceps"]', '[]', 'bodyweight', 'advanced', 1, 0, '3-0-1-0', 1, 'Dead hang start. Chest to bar. 3-second descent.'),
  ('db_biceps_curl', 'Dumbbell Biceps Curl', '["curl", "bicep curl", "db curl"]', 'arms', 'arms', '["biceps"]', '["forearms"]', 'dumbbell', 'beginner', 0, 0, '2-0-1-0', 1, 'Elbows pinned to sides. No swinging. Control the lowering.'),
  ('triceps_pushdown', 'Triceps Pushdown', '["pushdown", "tricep pushdown", "rope pushdown"]', 'arms', 'arms', '["triceps"]', '[]', 'cable', 'beginner', 0, 0, '2-0-1-0', 1, 'Elbows tucked. Full lockout, controlled return.'),
  ('hammer_curl', 'Hammer Curl', '["hammer", "neutral curl"]', 'arms', 'arms', '["biceps", "brachialis", "forearms"]', '[]', 'dumbbell', 'beginner', 0, 0, '2-0-1-0', 1, 'Neutral grip throughout. Builds forearm and elbow flexors.'),
  ('overhead_triceps_ext', 'Overhead Triceps Extension', '["tricep extension", "skullcrusher", "french press"]', 'arms', 'arms', '["triceps"]', '[]', 'dumbbell', 'beginner', 0, 0, '2-0-1-0', 1, 'Keep elbows pointing forward. Big stretch at the bottom.'),
  ('bodyweight_squat', 'Bodyweight Squat', '["air squat", "squat"]', 'lower', 'squat', '["quads", "glutes"]', '["core"]', 'bodyweight', 'beginner', 1, 0, '3-0-1-0', 1, 'Sit between the hips. Knees track over toes. Full depth you can control.'),
  ('box_squat', 'Box Squat', '["sit to stand", "chair squat"]', 'lower', 'squat', '["quads", "glutes"]', '[]', 'bodyweight', 'beginner', 1, 0, '3-0-1-0', 1, 'Sit back to a box/chair, stand tall. Easiest squat regression.'),
  ('goblet_squat', 'Goblet Squat', '["goblet", "db squat"]', 'lower', 'squat', '["quads", "glutes", "core"]', '[]', 'dumbbell', 'beginner', 1, 0, '3-0-1-0', 1, 'Hold dumbbell at chest. Sit into your heels. 3-second descent.'),
  ('leg_press', 'Leg Press (machine)', '["leg press", "machine squat"]', 'lower', 'squat', '["quads", "glutes"]', '[]', 'machine', 'intermediate', 1, 0, '3-0-1-0', 1, 'Foot placement mid-platform. 3-second descent. Don''t lock out at top.'),
  ('db_front_squat', 'Dumbbell Front Squat', '["db front squat"]', 'lower', 'squat', '["quads", "glutes", "core"]', '[]', 'dumbbell', 'intermediate', 1, 0, '3-0-1-0', 1, 'Dumbbells on shoulders. Elbows forward. 3-second descent.'),
  ('split_squat', 'Split Squat', '["static lunge", "db split squat"]', 'lower', 'squat', '["quads", "glutes"]', '["hamstrings", "core"]', 'dumbbell', 'intermediate', 1, 1, '3-0-1-0', 1, 'Feet split, drop straight down. Front-leg focus. Per side.'),
  ('bulgarian_split_squat', 'Bulgarian Split Squat', '["bulgarian", "rear foot elevated", "rfess"]', 'lower', 'squat', '["quads", "glutes"]', '["hamstrings", "core"]', 'dumbbell', 'intermediate', 1, 1, '3-0-1-0', 1, 'Rear foot on a bench. Stay tall. Brutal but joint-friendly. Per side.'),
  ('walking_lunge', 'Walking Lunge', '["lunge", "db lunge"]', 'lower', 'squat', '["quads", "glutes"]', '["hamstrings", "core"]', 'dumbbell', 'intermediate', 1, 1, '3-0-1-0', 1, 'Step into a lunge, drive through the front heel. Per side.'),
  ('barbell_front_squat', 'Barbell Front Squat', '["front squat"]', 'lower', 'squat', '["quads", "glutes", "core"]', '[]', 'barbell', 'advanced', 1, 0, '3-0-1-0', 0, 'Clean grip or crossed-arm. Elbows high throughout.'),
  ('barbell_back_squat', 'Barbell Back Squat', '["back squat", "squat"]', 'lower', 'squat', '["quads", "glutes"]', '["hamstrings", "lower_back", "core"]', 'barbell', 'advanced', 1, 0, '3-0-1-0', 0, 'Bar on upper traps. Brace, sit between the hips. Heavy spinal load.'),
  ('glute_bridge', 'Glute Bridge', '["bridge", "floor bridge"]', 'lower', 'hinge', '["glutes"]', '["hamstrings"]', 'bodyweight', 'beginner', 1, 0, '3-0-1-0', 1, 'Feet flat, drive hips up, squeeze at the top. Floor regression for hinging.'),
  ('hip_thrust', 'Hip Thrust', '["hip thruster", "db hip thrust"]', 'lower', 'hinge', '["glutes", "hamstrings"]', '[]', 'dumbbell', 'beginner', 1, 0, '3-0-1-0', 1, 'Upper back on bench. Squeeze at the top. 2-second hold.'),
  ('db_romanian_deadlift', 'Dumbbell Romanian Deadlift', '["db rdl", "romanian deadlift", "stiff leg"]', 'lower', 'hinge', '["hamstrings", "glutes", "lower_back"]', '[]', 'dumbbell', 'beginner', 1, 0, '3-0-1-0', 1, 'Soft knees. Push hips back. 3-second descent. Feel the hamstring stretch.'),
  ('kb_swing', 'Kettlebell Swing', '["swing", "kb swing", "russian swing"]', 'lower', 'hinge', '["glutes", "hamstrings"]', '["lower_back", "core"]', 'kettlebell', 'intermediate', 1, 0, NULL, 1, 'Hip snap, not a squat. Bell floats to chest height. Explosive but controlled.'),
  ('back_extension', 'Back Extension', '["hyperextension", "45 degree back ext"]', 'lower', 'hinge', '["lower_back", "glutes", "hamstrings"]', '[]', 'machine', 'intermediate', 1, 0, '3-0-1-0', 1, 'Hinge at the hips, round nothing. Stop at a straight line.'),
  ('single_leg_rdl', 'Single-Leg Romanian Deadlift', '["sl rdl", "single leg deadlift"]', 'lower', 'hinge', '["hamstrings", "glutes"]', '["lower_back", "core"]', 'dumbbell', 'intermediate', 1, 1, '3-0-1-0', 1, 'Hips square, reach the weight down one leg. Balance + hamstring. Per side.'),
  ('trap_bar_deadlift', 'Trap-Bar Deadlift', '["trap bar", "hex bar deadlift"]', 'lower', 'hinge', '["hamstrings", "glutes", "quads", "lower_back"]', '[]', 'barbell', 'intermediate', 1, 0, '3-0-1-0', 1, 'Neutral spine. Drive the floor away. One of the safest deadlift variations.'),
  ('barbell_deadlift', 'Conventional Deadlift', '["deadlift", "conventional", "bb deadlift"]', 'lower', 'hinge', '["hamstrings", "glutes", "lower_back", "traps"]', '[]', 'barbell', 'advanced', 1, 0, '3-0-1-0', 0, 'Bar over mid-foot. Lat engagement before the pull.'),
  ('barbell_rdl', 'Barbell Romanian Deadlift', '["barbell rdl", "stiff leg deadlift"]', 'lower', 'hinge', '["hamstrings", "glutes"]', '["lower_back"]', 'barbell', 'advanced', 1, 0, '3-0-1-0', 0, 'Bar close, hips back, flat back. Heavier loading than the DB version.'),
  ('leg_extension', 'Leg Extension', '["quad extension", "knee extension"]', 'lower', 'squat', '["quads"]', '[]', 'machine', 'beginner', 0, 0, '2-0-1-0', 1, 'Control the lowering. Pause briefly at lockout.'),
  ('leg_curl', 'Leg Curl', '["hamstring curl", "lying leg curl", "seated leg curl"]', 'lower', 'hinge', '["hamstrings"]', '[]', 'machine', 'beginner', 0, 0, '2-0-1-0', 1, 'Squeeze the hamstrings, slow return. Lying or seated.'),
  ('calf_raise', 'Standing Calf Raise', '["calf raise", "calves"]', 'lower', 'squat', '["calves"]', '[]', 'bodyweight', 'beginner', 0, 0, '2-0-1-0', 1, 'Full stretch at the bottom, pause at the top.'),
  ('step_up', 'Step-Up', '["box step up", "db step up"]', 'lower', 'squat', '["quads", "glutes"]', '["hamstrings"]', 'dumbbell', 'beginner', 1, 1, '3-0-1-0', 1, 'Drive through the top foot. Control the way down. Per side.'),
  ('dead_bug', 'Dead Bug', '["deadbug"]', 'core', 'core', '["abs", "core"]', '["hip_flexors"]', 'bodyweight', 'beginner', 0, 0, NULL, 1, 'Low back pinned to floor. Opposite arm/leg, slow and controlled.'),
  ('plank', 'Front Plank', '["plank", "front hold"]', 'core', 'core', '["core", "abs"]', '["front_delt"]', 'bodyweight', 'beginner', 0, 0, NULL, 1, 'Straight line head to heels. Squeeze glutes. Hold for time.'),
  ('side_plank', 'Side Plank', '["side hold"]', 'core', 'core', '["obliques", "core"]', '["glutes"]', 'bodyweight', 'beginner', 0, 1, NULL, 1, 'Stack the hips, lift them high. Hold for time. Per side.'),
  ('bird_dog', 'Bird Dog', '["quadruped reach"]', 'core', 'core', '["core", "lower_back"]', '["glutes"]', 'bodyweight', 'beginner', 0, 1, NULL, 1, 'Opposite arm and leg, no rotation through the hips. Per side.'),
  ('pallof_press', 'Pallof Press', '["anti-rotation press", "pallof"]', 'core', 'core', '["obliques", "core"]', '[]', 'cable', 'intermediate', 0, 1, NULL, 1, 'Resist the cable pulling you to the side. Press straight out. Per side.'),
  ('cable_crunch', 'Cable Crunch', '["kneeling crunch"]', 'core', 'core', '["abs", "core"]', '[]', 'cable', 'intermediate', 0, 0, '2-0-1-0', 1, 'Crunch with the abs, hips stay put. Round the spine down.'),
  ('hanging_knee_raise', 'Hanging Knee Raise', '["hanging knee", "knee raise"]', 'core', 'core', '["abs", "hip_flexors"]', '["forearms"]', 'bodyweight', 'intermediate', 0, 0, NULL, 1, 'No swinging. Curl the knees up and the pelvis under.'),
  ('ab_wheel', 'Ab Wheel Rollout', '["rollout", "ab roller"]', 'core', 'core', '["abs", "core"]', '["lats", "front_delt"]', 'bodyweight', 'advanced', 1, 0, NULL, 0, 'Roll out only as far as you can keep a flat back. High demand on the trunk.'),
  ('suitcase_carry', 'Suitcase Carry', '["suitcase walk", "single arm carry"]', 'carry', 'carry', '["obliques", "core"]', '["forearms", "traps"]', 'dumbbell', 'beginner', 1, 1, NULL, 1, 'One weight, walk tall, don''t lean. Anti-lateral-flexion. Per side.'),
  ('farmers_carry', 'Farmer''s Carry', '["farmers walk", "loaded carry"]', 'carry', 'carry', '["forearms", "traps", "core"]', '["glutes"]', 'dumbbell', 'intermediate', 1, 0, NULL, 1, 'A weight in each hand, walk tall and controlled. Grip + posture + everything.'),
  ('kb_front_rack_carry', 'Kettlebell Front-Rack Carry', '["front rack carry", "rack walk"]', 'carry', 'carry', '["core", "front_delt"]', '["forearms"]', 'kettlebell', 'intermediate', 1, 1, NULL, 1, 'Bell(s) in the front rack, ribs down, breathe. Per side if single.'),
  ('hip_90_90', 'Hip 90/90 Stretch', '["90 90", "hip stretch"]', 'mobility', 'mobility', '["hips"]', '[]', 'bodyweight', 'beginner', 0, 0, NULL, 1, 'Gentle. No pain.'),
  ('thoracic_rotation', 'Thoracic Rotation', '["t-spine rotation", "open book"]', 'mobility', 'mobility', '["upper_back"]', '[]', 'bodyweight', 'beginner', 0, 0, NULL, 1, 'Sit on heels, rotate slowly.'),
  ('band_pull_apart', 'Band Pull-Apart', '["pull apart", "band pulls"]', 'mobility', 'mobility', '["rear_delt", "mid_back"]', '[]', 'band', 'beginner', 0, 0, NULL, 1, 'Light band. Focus on rear-delt squeeze.'),
  ('cat_cow', 'Cat-Cow', '["cat camel"]', 'mobility', 'mobility', '["spine"]', '[]', 'bodyweight', 'beginner', 0, 0, NULL, 1, 'Slow and controlled.'),
  ('world_greatest_stretch', 'World''s Greatest Stretch', '["wgs", "lunge twist"]', 'mobility', 'mobility', '["hips", "upper_back"]', '[]', 'bodyweight', 'beginner', 0, 0, NULL, 1, 'Lunge, hand down, rotate open. Move slowly through the range.'),
  ('ankle_mobility', 'Ankle Mobility Drill', '["ankle rock", "dorsiflexion drill"]', 'mobility', 'mobility', '["ankles"]', '[]', 'bodyweight', 'beginner', 0, 0, NULL, 1, 'Knee over toes, heel down. Gentle rocking.'),
  ('dead_hang', 'Dead Hang', '["bar hang", "hang"]', 'mobility', 'mobility', '["lats", "forearms"]', '["front_delt"]', 'bodyweight', 'beginner', 0, 0, NULL, 1, 'Relax and breathe. Decompresses the shoulders and spine.'),
  ('incline_walk', 'Incline Treadmill Walk', '["treadmill walk", "incline walk"]', 'conditioning', 'conditioning', '["quads", "calves"]', '["glutes"]', 'machine', 'beginner', 0, 0, NULL, 1, 'Steady incline walk. Conversational pace.'),
  ('stationary_bike', 'Stationary Bike', '["bike", "cycling", "spin bike"]', 'conditioning', 'conditioning', '["quads"]', '["glutes", "hamstrings"]', 'machine', 'beginner', 0, 0, NULL, 1, 'Low-impact steady cardio. Keep cadence smooth.'),
  ('rower', 'Rowing Machine', '["row erg", "erg", "concept2"]', 'conditioning', 'conditioning', '["lats", "quads", "glutes"]', '["hamstrings", "biceps", "core"]', 'machine', 'intermediate', 1, 0, NULL, 1, 'Legs-core-arms on the drive, reverse on the return. Full-body conditioning.'),
  ('elliptical', 'Elliptical', '["cross trainer"]', 'conditioning', 'conditioning', '["quads", "glutes"]', '["hamstrings"]', 'machine', 'beginner', 0, 0, NULL, 1, 'Low-impact steady cardio.'),
  ('kb_circuit', 'Kettlebell Conditioning Circuit', '["kb circuit", "kettlebell complex"]', 'conditioning', 'conditioning', '["glutes", "quads", "shoulders"]', '["core", "forearms"]', 'kettlebell', 'advanced', 1, 0, NULL, 0, 'High heart-rate complex. Skip or scale on low-energy days.');

UPDATE movements SET progresses_to='db_front_squat', regresses_to=NULL WHERE id='goblet_squat';
UPDATE movements SET progresses_to='barbell_front_squat', regresses_to='goblet_squat' WHERE id='db_front_squat';
UPDATE movements SET progresses_to=NULL, regresses_to='db_front_squat' WHERE id='barbell_front_squat';
UPDATE movements SET progresses_to=NULL, regresses_to='goblet_squat' WHERE id='leg_press';
UPDATE movements SET progresses_to='trap_bar_deadlift', regresses_to=NULL WHERE id='db_romanian_deadlift';
UPDATE movements SET progresses_to='barbell_deadlift', regresses_to='db_romanian_deadlift' WHERE id='trap_bar_deadlift';
UPDATE movements SET progresses_to=NULL, regresses_to='trap_bar_deadlift' WHERE id='barbell_deadlift';
UPDATE movements SET progresses_to='db_bench_press', regresses_to=NULL WHERE id='push_up';
UPDATE movements SET progresses_to='barbell_bench_press', regresses_to='push_up' WHERE id='db_bench_press';
UPDATE movements SET progresses_to=NULL, regresses_to='push_up' WHERE id='incline_db_press';
UPDATE movements SET progresses_to=NULL, regresses_to='db_bench_press' WHERE id='barbell_bench_press';
UPDATE movements SET progresses_to='barbell_ohp', regresses_to=NULL WHERE id='db_shoulder_press';
UPDATE movements SET progresses_to=NULL, regresses_to='db_shoulder_press' WHERE id='barbell_ohp';
UPDATE movements SET progresses_to='db_row', regresses_to=NULL WHERE id='chest_supported_row';
UPDATE movements SET progresses_to='barbell_row', regresses_to=NULL WHERE id='db_row';
UPDATE movements SET progresses_to='barbell_row', regresses_to=NULL WHERE id='cable_row';
UPDATE movements SET progresses_to=NULL, regresses_to='db_row' WHERE id='barbell_row';
UPDATE movements SET progresses_to='assisted_pull_up', regresses_to=NULL WHERE id='lat_pulldown';
UPDATE movements SET progresses_to='pull_up', regresses_to='lat_pulldown' WHERE id='assisted_pull_up';
UPDATE movements SET progresses_to=NULL, regresses_to='assisted_pull_up' WHERE id='pull_up';
